site_name: Home Buttons

repo_url: https://github.com/nplan/HomeButtons
repo_name: nplan/HomeButtons

nav:
  - Home: index.md
  - Home Buttons Mini:
      - mini/index.md
      - Getting Started: mini/setup.md
      - User Guide: mini/user_guide.md
      - MQTT Topics: mini/mqtt_topics.md
      - Firmware Update: mini/update.md
  - Home Buttons:
      - original/index.md
      - Getting Started: original/setup.md
      - User Guide: original/user_guide.md
      - MQTT Topics: original/mqtt_topics.md
      - Soldering: original/soldering.md
      - Hardware Hacks: original/hardware_hacks.md
      - Firmware Update: original/update.md
  - Support:
      - Common Issues: help.md
      - Minimal Setup: minimal.md

theme:
  name: material
  logo: assets/home_buttons_logo.svg
  favicon: assets/home_buttons_logo.svg
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

    # Palette toggle for light mode
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: cyan
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: cyan
      accent: orange

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-F5LT7JQ5LS

copyright: Copyright &copy; 2022 - 2023 PLab
